spring:
 datasource:
  username: root
  password: 1234
  url: jdbc:mysql://localhost:3306/user_details_db
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
   
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    format_sql: true
  
server:
 port: 9100
  
  